- index.d.ts
- package.json
> Add TS types

- lib/handlers/authorize-handler.js
- test/integration/handlers/authorize-handler_test.js
This pr is related to issue #89, with point 13 and 20 (original pr https://github.com/oauthjs/node-oauth2-server/pull/576 and https://github.com/oauthjs/node-oauth2-server/pull/649 respectively).
It adds the missing state parameter.
The reference issue is the #89.
Yes, and updated already existent tests.
RFC6749, section 4.1.2.1
> Supported state in case of denial

- lib/handlers/authorize-handler.js
- test/integration/handlers/authorize-handler_test.js
Implements https://github.com/oauthjs/node-oauth2-server/pull/473/files
#89 
Authorize handler
Added integration tests
https://datatracker.ietf.org/doc/html/rfc6749.html#section-4.1.1
Clone, checkout branch, run tests
> fix(handlers): skip varcheck for state when allowEmptyState

- docs/model/spec.rst
This is a "doc" improvement pr.
It adds some missing `return` statement in the examples.
This pr is related to issue #89, point 9, original pr https://github.com/oauthjs/node-oauth2-server/pull/561.
> Fixed misssing return statement in doc

- lib/handlers/authenticate-handler.js
- test/integration/handlers/authenticate-handler_test.js
This adds the `WWW-Authenticate` header for `InvalidRequestError`, `InvalidTokenError`,
and `InsufficientScopeError`, as specified in RFC 6750, Section 3
The original pr is https://github.com/oauthjs/node-oauth2-server/pull/646
Fixes issue #89, point 18.
Yes
RFC 6750, Section 3
> Set WWW-Authenticate header for invalid requests

- lib/handlers/authenticate-handler.js
- test/unit/handlers/authenticate-handler_test.js
This pr fixes the regex for checking the bearer token.
Issue #89, point 15, original pr https://github.com/oauthjs/node-oauth2-server/pull/614
Yes
RFC 6750 | OAuth 2.0 Bearer Token Usage | Section 2.1
https://tools.ietf.org/html/rfc6750#section-2.1
> Bearer regular expression matching in authenticate handler

- CHANGELOG.md
- docs/misc/extension-grants.rst
- package-lock.json
- package.json
Hi,
just updated a doc example, which seems fine to me.
I have left classes on purpose, since it is a more modern JS syntax, and probably also this code base is moving to more modern JS. 
Regards.
Edit by @jankapunkt: Fixed issue 89, point 5, original issue 530
>   Update extension-grants.rst with example

- lib/grant-types/refresh-token-grant-type.js
- test/integration/grant-types/refresh-token-grant-type_test.js
The main problem is various errors were identical in the Refresh Token Grant file. While working on an express/mongodb adapter I kept erroring out at the client check. Well the client check error is the same error that exist in like 5 other places. Just changing the verbiage alone would help in diagnosing the problem.
[https://github.com/node-oauth/node-oauth2-server/blob/master/lib/grant-types/refresh-token-grant-type.js](Refresh Grant Type)
si
Its just the error verbiage the logic remains untouched.
No new features just changing some text.
https://github.com/node-oauth/node-oauth2-server/pull/140
> RefreshTokenGrant: update error messages

- README.md
I added the seven badges requested in the linked issue into the `README`. 
The badges have been placed between the `Complete, compliant and well tested module for implementing an OAuth2 server in [Node.js](https://nodejs.org/).` and `NOTE: This project has been forked from...` lines as specified.
All badges have been added in the Markdown format.
#163
This PR only affects the `README` doc.
N/A
N/A
N/A
> docs: add badges to README #163

- index.d.ts
- lib/handlers/authorize-handler.js
- test/integration/handlers/authorize-handler_test.js
- test/unit/handlers/authorize-handler_test.js
For getAuthorizationCode it is expected that the code contains a codeChallenge and a codeChallengeMethod but in saveAuthorizationCode it is not saved.
By adding the possibility to save codeChallenge and codeChallengeMethod the PKCE flow now works without any other changes. 
https://github.com/node-oauth/node-oauth2-server/issues/76
Authorization Code Flow with PKCE
Yes
OAuth 2.0 RFC 7636
First authorize
```
curl --location --request POST 'http://localhost:8081/oauth2/authorize' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=test' \
--data-urlencode 'scope=openid' \
--data-urlencode 'redirect_uri=http://localhost:5000/callback' \
--data-urlencode 'state=e3e96ed8-889d-4dac-a680-6a47f5efbb14' \
--data-urlencode 'response_type=code' \ …
```
> Save code challenge with authorization code

- .github/workflows/tests-release.yml
- .github/workflows/tests.yml
- index.d.ts
- lib/grant-types/authorization-code-grant-type.js
- lib/handlers/authorize-handler.js
- lib/handlers/token-handler.js
- lib/pkce/pkce.js
- lib/utils/crypto-util.js
- lib/utils/string-util.js
- lib/utils/token-util.js
- package.json
- test/integration/handlers/authorize-handler_test.js
- test/integration/handlers/token-handler_test.js
- test/unit/grant-types/authorization-code-grant-type_test.js
- test/unit/handlers/authorize-handler_test.js
- test/unit/pkce/pkce_test.js
Our CI for Node 16 and 18 for test release is somewhat broken :thinking:
> merge release 4.3.0 into master

- lib/handlers/authorize-handler.js
- test/integration/handlers/authorize-handler_test.js
This is an obvious fix, you can see the async function being defined a couple lines down the file so this needs to be awaited 
#204
Authorization
> Fix generateAuthorizationCode not being awaited

- index.d.ts
When you do not implement `verifyScope` method in the model, TypeScript currently throws an error even though you do not need to implement this method in all cases. There are a lot of instances where `verifyScope` method is optional. There is already some error mechanisms to throw errors in cases where `verifyScope` is required and is not implemented. So making this implementation optional in models.
https://github.com/node-oauth/node-oauth2-server/issues/202
Typings
NA
NA
TypeScript will not throw errors anymore if you do not implement `verifyScope` when using your own authenticate handler.
> Marked verifyScope function as optional in model types.

- index.d.ts
Removed callback support in TypeScript typings for release 5.0.0
https://github.com/node-oauth/node-oauth2-server/issues/210
Types
NA
NA
NA
> Removed callback support in typings file.

- .readthedocs.yml
- docs/api/errors/access-denied-error.rst
- docs/api/errors/insufficient-scope-error.rst
- docs/api/errors/invalid-argument-error.rst
- docs/api/errors/invalid-client-error.rst
- docs/api/errors/invalid-grant-error.rst
- docs/api/errors/invalid-request-error.rst
- docs/api/errors/invalid-scope-error.rst
- docs/api/errors/invalid-token-error.rst
- docs/api/errors/oauth-error.rst
- docs/api/errors/server-error.rst
- docs/api/errors/unauthorized-client-error.rst
- docs/api/errors/unauthorized-request-error.rst
- docs/api/errors/unsupported-grant-type-error.rst
- docs/api/errors/unsupported-response-type-error.rst
- docs/api/oauth2-server.rst
- docs/api/request.rst
- docs/api/response.rst
- docs/conf.py
- docs/docs/adapters.rst
- docs/docs/getting-started.rst
- docs/index.rst
- docs/misc/extension-grants.rst
- docs/misc/migrating-v2-to-v3.rst
- docs/misc/pkce.rst
- docs/model/overview.rst
- docs/model/spec.rst
- docs/npm_conf.py
This updates our docs at https://node-oauthoauth2-server.readthedocs.io/en/latest/index.html to be up to date
Note: merged into master in order to apply changes
Build status for this PR: [![Documentation Status](https://readthedocs.org/projects/node-oauthoauth2-server/badge/?version=docs-update)](https://node-oauthoauth2-server.readthedocs.io/en/latest/?badge=docs-update)
Preview of the docs build: https://node-oauthoauth2-server.readthedocs.io/en/docs-update/
> docs: fix links and cover missing topics

- index.d.ts
- lib/grant-types/client-credentials-grant-type.js
- test/integration/grant-types/client-credentials-grant-type_test.js
`getUserFromClient` was not awaited in client credentials grant, this results in a promise being passed to the `validateScope` function in the model instead of the actual user.
#217 217
Client Credentials grant
NA
> Fixed `getUserFromClient` not being awaited in client credentials grant.

- docs/model/spec.rst
Now, the documentation for model methods `getAuthorizationCode` and `revokeAuthorizationCode` consistently refer to `code.authorizationCode` rather than `code.code`.
Closes #216.
Documentation only -- specifically for `revokeAuthorizationCode` and `getAuthorizationCode`.
N/A
N/A
N/A
> Docs: Replace `code.code` with `code.authorizationCode` (attempt 2)

- lib/models/token-model.js
- lib/utils/date-util.js
- test/unit/models/token-model_test.js
- test/unit/utils/date-util__test.js
I saw open issue #212 for converting ES5-style classes to modern class syntax, and it seemed like a nice issue for new contributors to help chip away at (small refactoring that can be covered by unit tests; no functional changes).
So, I am submitting a PR to do that for the `TokenModel` class. Hopefully it is helpful! I'm happy to make changes to better match the desired styles/conventions of the repo as necessary. Or, if this PR isn't in line with what you had in mind, I won't be offended if you'd prefer to close it.
Overview:
- Converted `TokenModel` to an ES6-style class (previously it was an ES5-style "constructor function").
- Extracted a utility function for getting lifetime in seconds from expiration date into a `date-util` module.
- Updated unit tests to cover the affected code. …
> Convert TokenModel to an ES6 class and extract utils function for calculating lifetime

- lib/grant-types/authorization-code-grant-type.js
- lib/grant-types/client-credentials-grant-type.js
- lib/grant-types/password-grant-type.js
Fixes a critical bug mentioned in #64
#64 
Scope validation
NA
NA
> Fix critical scope validation bug

- lib/grant-types/abstract-grant-type.js
- lib/grant-types/authorization-code-grant-type.js
- lib/grant-types/client-credentials-grant-type.js
- lib/grant-types/password-grant-type.js
Fixes critical bug for 4.x version
#64 
validate scope
NA
NA
NA
> hotfix: fixed critical scope validation bug for 4.x

- lib/request.js
- lib/response-types/code-response-type.js
- lib/response-types/token-response-type.js
- lib/response.js
- test/unit/request_test.js
- test/unit/response_test.js
Chipping away at #212 by converting four more classes:
- Request
- Response
- CodeResponseType
- TokenResponseType
(Do note that TokenResponseType's constructor simply throws a not implemented error, though. So that conversion was easy. 😉)
A few checkboxes of #212 (but not the whole thing).
Specifically the classes noted above, which affect pretty much everything (since Request/Response are core parts of the interface). But, there are no functional changes.
I did not update the tests, but these files are already covered under the existing tests, which should continue to pass after this refactoring.
N/A
N/A
> Convert Request, Response, CodeResponseType, TokenResponseType to ES6 classes

- lib/grant-types/authorization-code-grant-type.js
Revoke authorization code before validating redirect uri
fixes #82
fixes https://github.com/oauthjs/node-oauth2-server/issues/637
Revoking authorization codes
NA
NA
NA
> revoke code before validating redirect uri

- README.md
Made the npm badges on the readme clickable
> made badges clickable

- lib/handlers/authenticate-handler.js
Validate the bearer token with the correct regex as described in the spec.
fixes #127 
authenticate handler
already existed
https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
NA
> Improve bearer validation

- test/integration/handlers/authorize-handler_test.js
Removed an invalid bearer token that was used in a test.
#234
Yes
> remove invalid bearer token that was used in test

- docs/model/spec.rst
- index.d.ts
- lib/grant-types/password-grant-type.js
- test/integration/grant-types/password-grant-type_test.js
- test/unit/grant-types/password-grant-type_test.js
Pass the client to the `getUser` function of the model. This makes it possible to retrieve the user based on the client.
#114 
Password Grant Type
Yes
> Support for retrieving user based on client

- index.d.ts
If a request is received with no scope in the request body, then the `scope` argument to `validateScope` is undefined instead of an array. This change updates the typings to be consistent with that behaviour.
resolves #264
https://github.com/node-oauth/node-oauth2-server/blob/v5.0.0/lib/utils/scope-util.js#L10-L12
n/a
n/a
See issue.
> fix: update typing for validateScope making scope an optional parameter

- index.d.ts
> fix(types): type declaration for `AuthenticateOptions.scope`

- .github/workflows/tests.yml
This adds a NodeJS 22 test to our test suite
> ci: add node 22 to test matrix

- lib/utils/token-util.js
There are some wasted CPU cycles when generating the random tokens.
There's no need to generate extra random bytes only to hash them. A random input will lead to a random hash being generated, but the random input is enough in its own right and does not need to be hashed to make it any more or less secure. The amount of entropy is capped at 32 bytes when hashed, so we may as well just provide 32 random bytes.
As an added bonus, this also returns the method to a true non-blocking async function.
> perf: random tokens do not need to be hashed

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/tests-release.yml
- .github/workflows/tests.yml
- .gitignore
- .npmignore
- .npmrc
- package-lock.json
This will help keep our github actions up-to-date.
I've also removed the `actions/cache` job because it's not actually needed as `actions/setup-node` can do caching itself. This does require us to commit a `package-lock.json` file, but that is good practice so I advocate to change that too!
> ci: add dependabot integration for github actions

- index.d.ts
- lib/handlers/authenticate-handler.js
- test/integration/handlers/authenticate-handler_test.js
In #267 some changes were made for compliance reasons where scopes should be treated as strings for our OAuth interfaces but as arrays of strings for internal purposes. As part of that change, we accidentally made the `scope` prop for the `authenticate` method only support strings.
This change remediates any potential backwards compatibility changes from v5.0 to v5.1
#307 & #267 
authenticate handler
✅
> fix: explicitly support array of strings for AuthenticateHandler.options

- index.d.ts
1. Don't use `| undefined` for props that are already declared optional (`undefined` is an implied value)
2. prefer using the [`Record`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) built-in type over object maps
> refactor(types): update types to be more concise

- index.d.ts
This fixes the typing issue with the Request constructor. 
Typescript typing is used to prevent runtime errors with compile time checks. 
In these lines https://github.com/node-oauth/node-oauth2-server/blob/cd81a3ae04814838a3cc300d003d9e41e391ba02/lib/request.js#L12-L22 , there are runtime errors thrown that are not reflected by the typescript typing and therefore not catchable by the Typescript compiler.
https://github.com/node-oauth/node-oauth2-server/issues/356#issuecomment-2966000161
Typing declarations
No
> fixed typing for Request constructor
